apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-config
  namespace: sock-shop
data:
  JAVA_OPTS: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  
